Remove references to objc_provider and remove force_load_direct_deps to support rules_apple > 3.15.0 (#934)
1) With rules_apple removing legacy objc_providers, rules_apple > 3.15.0
is no longer compatible with rules_ios due to
https://github.com/bazelbuild/rules_apple/pull/2611

2) Removing force load direct deps as its no longer needed in Bazel 7
https://github.com/bazel-ios/rules_ios/issues/862

```sh
ERROR: /Users/ssarad/Bazel/BUILD.bazel:3:15: in apple_framework_packaging rule 
Traceback (most recent call last):
	File "/Users/ssarad/.bazel_cache/output/external/rules_ios~/rules/framework.bzl", line 1109, column 48, in _apple_framework_packaging_impl
		bundle_outs = _bundle_dynamic_framework(ctx, is_extension_safe = is_extension_safe, avoid_deps = avoid_deps)
	File "/Users/ssarad/.bazel_cache/output/external/rules_ios~/rules/framework.bzl", line 888, column 44, in _bundle_dynamic_framework
		partials.framework_provider_partial(
	File "/Users/ssarad/.bazel_cache/output/external/rules_apple~/apple/internal/partials/framework_provider.bzl", line 94, column 5, in framework_provider_partial
		def framework_provider_partial(
Error: framework_provider_partial() got unexpected keyword argument: objc_provider

```

This PR is attempt to make rules_ios compatible with rules_apple +
remove the legacy code to force load direct deps as with Bazel 7,
`--incompatible_objc_alwayslink_by_default` does the same thing.

---------

Co-authored-by: Sarad <sarad.pant@capitalone.com>