Fix LLDB internal module compilation error
When LLDB compiles swiftmodules during attachment and `po` it is missing
some clang importer arguments. This adds missing copts directly to
LLDB in the lldbinit.

Note that I have also added a _example_ test case for LLDB and clarified some of
the requirments here. For now, it atleast documents this requirment:
```
Xcode project: bazel run tests/ios/xcodeproj:Test-Imports-App-Project
&& open tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/
Scheme: `TestImports-App`
Breakpoints: tests/ios/unit-test/test-imports-app/empty.swift:6
Breakpoints: tests/ios/unit-test/test-imports-app/empty.swift:15
Xcode Version: 12.5.1
```

Longer term, can "Reverse sherlock" some LLDB automation testing from
swift-LLDB to verify debugging of many examples. Testing is further
blocked by getting the debugger working on the examples. As of today,
the examples just don't work on master
https://github.com/bazel-ios/rules_ios/issues/281