Fix static/framework `vendored_xcframeworks` on arm64 sim
# Summary
The autolink functionality was disabled in `rules_apple` causing the static frameworks processed by `import_middleman` to break (in AFAIK, https://github.com/bazelbuild/rules_swift/commit/7d8769a9d5024200da8a34999e5934b23f441e90 ).

- `//tests/ios/xcframeworks/Basic/BasicXCFramework:BasicXCFrameworkStatic` is now the `(linkage => static, packaging => framework)` test case that was missing.
- `//tests/ios/xcframeworks/Basic/BasicXCFramework:BasicXCFrameworkDynamic` remains the test case for `(linkage => dynamic, packaging => framework)`.

# Issue
```
$ bazelisk build //tests/ios/xcframeworks/Basic:XCFrameworksApp
INFO: Invocation ID: 3b68d6dc-5ef1-4aef-aa27-6cb1376391dc
INFO: Analyzed target //tests/ios/xcframeworks/Basic:XCFrameworksApp (3 packages loaded, 109 targets configured).
INFO: Found 1 target...
ERROR: /Users/matt.robinson/Developer/rules_ios/rules_ios/tests/ios/xcframeworks/Basic/BUILD.bazel:15:16: Linking tests/ios/xcframeworks/Basic/XCFrameworksApp_bin failed: (Exit 1): wrapped_clang failed: error executing command (from target //tests/ios/xcframeworks/Basic:XCFrameworksApp)
  (cd /private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/sandbox/darwin-sandbox/1460/execroot/build_bazel_rules_ios && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    PATH=/Users/matt.robinson/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.0.0-darwin-arm64/bin:/Users/matt.robinson/.rbenv/shims:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/wrapped_clang @bazel-out/ios-sim_arm64-min10.0-applebin_ios-ios_sim_arm64-dbg-ST-65c06fec92bf/bin/tests/ios/xcframeworks/Basic/XCFrameworksApp_bin-2.params)
# Configuration: 23b452a416a6e296c7e6f932d44de118bfd1a18fbd7773b6145b06e2edc312fa
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld: warning: object file (bazel-out/ios-sim_arm64-applebin_ios-ios_sim_arm64-dbg-ST-2a0e8ccdcbc3/bin/tests/ios/xcframeworks/Basic/libxcframeworks_swift.a(Foo.swift.o)) was built for newer iOS Simulator version (16.2) than being linked (14.0)
ld: warning: Could not find or use auto-linked framework 'BasicXCFrameworkStatic'
Undefined symbols for architecture arm64:
  "_$s22BasicXCFrameworkStatic3FooC3baryyF", referenced from:
      _$s12xcframeworks3fooyyF in libxcframeworks_swift.a(Foo.swift.o)
  "_$s22BasicXCFrameworkStatic3FooC3numACSi_tcfC", referenced from:
      _$s12xcframeworks3fooyyF in libxcframeworks_swift.a(Foo.swift.o)
  "_$s22BasicXCFrameworkStatic3FooCMa", referenced from:
      _$s12xcframeworks3fooyyF in libxcframeworks_swift.a(Foo.swift.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //tests/ios/xcframeworks/Basic:XCFrameworksApp failed to build
INFO: Elapsed time: 0.668s, Critical Path: 0.50s
INFO: 5 processes: 3 internal, 1 darwin-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
```