Pass compilation context via swift info in framework rule due to rules_swift 2.1.1 (#907)
same idea as https://github.com/bazel-ios/rules_ios/pull/906 this time
is for framework rule.

The CI error trying to fix in this PR is:
```
# Execution platform: @local_config_platform//:host
error: generate-pch command failed with exit code 1 (use -v to see invocation)
tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h:1:9: error: 'TestImports-App/Header2.h' file not found
#import <TestImports-App/Header2.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header 'bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-c2aefc9133a8/bin/_pch_output_dir/TestImports-App-Bridging-Header-swift_28IU2BV1DK30K-clang_1FNSWCOAS4SUQ.pch' for bridging header 'tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h'
2 errors generated.
error: fatalError
```
This time this header is brought in by the framework rule

The idea here is to create the `clang_module` based of the same
compilation context as CcInfo and construct the final swift info based
on it. With this no need to differentiate based on if VFS turned on or
not